[tool.poetry]
name = "openstates-geo"
version = "2.0.0"
description = ""
authors = ["James Turk <james@openstates.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
us = "^1.0.0"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
