version: 2

jobs:
  build:
    docker:
      # Running docker within Docker isn't typically recommended.
      # However, this setup within CircleCI allows us to avoid
      # having to push the image to a Docker registry, and the
      # subsequent webhook to run the completed image; CircleCI's
      # standard steps don't allow building and running a Docker
      # image in-place.
      - image: docker/compose:1.24.0-rc1
    steps:
      - checkout
      # Unfortunately, Docker layer caching is a premium feature
      # for CircleCI 2, so all layers must be rebuilt during
      # each CI run
      # https://circleci.com/docs/2.0/docker-layer-caching/
      - setup_remote_docker
      - run: docker-compose up make-tiles
