version: 2

jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: openstates/openstates-district-maps
    steps:
      # Since the CircleCI image will be from a previous commit,
      # do a fresh clone of the repository; see README for more info
      - run: |
          git clone https://github.com/openstates/openstates-district-maps.git &&
          cd openstates-district-maps &&
          ./make-tiles.sh
