version: 2
jobs:
  build:
    docker:
      - image: nikolaik/python-nodejs
    working_directory: ~/openstates-district-maps
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            npm install
      - run: ./make-tiles.sh
